### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by ghost** [tokiroto/HyakusenrenmaTestTask#1]
The code appears to be doing browser detection and applying media queries to change the styles, but we need this to be fully responsive. So styles should adjust based on resizing the browser.

**Comment by tokiroto** [comment]
**hyakurendev**,  as I understand your idea, I will get rid of those media queries in tags.sass file, and implement the way it has been done in bootstrap by using columns and table instead. Am I on the right track? Please confirm.

**Comment by ghost** [comment]
@tokiroto Yes, instead of using device detection to apply different styles, when the browser window is resized the elements should adapt. This is like it has been done in bootstrap with their responsive grid.
Please note the requirement not to use bootstrap outright, although you can use it as a model if you like.

**Comment by tokiroto** [comment]
Added changes ( commit e1c31efe150fc92b02587beb94db445a7ef207bd ).

**Comment by ghost** [comment]
@tokiroto There still seems to be a problem with the responsiveness.

https://youtu.be/XU1DpYCvZz0

I took a screen recording of the problem with a comparison to a fully-responsive implementation.
Could you please confirm?

**Comment by tokiroto** [comment]
@hyakurendev I was testing in dev mode, responsiveness, when you drag the track to resize the window, and it worked just fine. Let me try to fix it fast, if you want resize the screen.

**Comment by tokiroto** [comment]
Added changes ( commit 8276eecadc2a36ad37b4c1322784f98f70fdcd6a ).

**Comment by ghost** [comment]
@tokiroto I see the issue now. Thank you for the quick fix. 
In general, I would avoid using `min-device-width` and would recommend using `min-width` instead, as it simplifies responsive design/development.

Please refer to this article for more detailed information:
https://www.sitepoint.com/media-queries-width-vs-device-width/

Unless you are using `min-device-width` to target specific devices, could you remove the `min-device-width` queries? This will be final step until closing this issue.

**Comment by tokiroto** [comment]
Ok, let me try, as I am already at work.

**Comment by tokiroto** [comment]
Addressed changes ( commit  09147f54e11b1cb07ad84e79163b64005b673c27 ).

**Comment by ghost** [comment]
@tokiroto Thank you for fixing this final change. This looks good to me. Will close this issue now.
Great job on the code review 👍
