### ISSUE TITLE
Clean import paths

### ISSUE THREAD

**Issue by ghost** [tokiroto/HyakusenrenmaTestTask#2]
https://github.com/tokiroto/HyakusenrenmaTestTask/blob/4868c479cb13531f1fc8d607822bd39480310e1b/app/styles/sass/base.sass#L1

Import paths should not have leading underscores [sass-lint: clean import paths]
(https://github.com/sasstools/sass-lint/blob/master/docs/rules/clean-import-paths.md)

**Comment by tokiroto** [comment]
Added changes ( commit 3d0f5e30d80c81503088d72837c03426d445279d ).

**Comment by ghost** [comment]
@tokiroto I think it was a good idea to extract your variables into a separate file. 👍 
Instead of doing an `@import 'variables` in multiple files, I'd recommend creating an `app.sass` file and using that to import all of your sass partials.

**Comment by tokiroto** [comment]
Added changes ( commit 9dfd56b093fdd9ef9b249011963f0474eb29eaff ).

**Comment by ghost** [comment]
Looks great! 👍
