### ISSUE TITLE
document head is missing some meta tags

### ISSUE THREAD

**Issue by ghost** [tokiroto/HyakusenrenmaTestTask#3]
https://github.com/tokiroto/HyakusenrenmaTestTask/blob/4868c479cb13531f1fc8d607822bd39480310e1b/app/index.html#L4

Please add the meta tags for charset, title, description and `<meta http-equiv="x-ua-compatible" content="ie=edge">`

**Comment by tokiroto** [comment]
Added changes ( commit 97687c219154d499692cd8ca2a83ed55dc77fd67).

**Comment by ghost** [comment]
@tokiroto LGTM 👍
