### ISSUE TITLE
Nesting depth

### ISSUE THREAD

**Issue by ghost** [tokiroto/HyakusenrenmaTestTask#4]
https://github.com/tokiroto/HyakusenrenmaTestTask/blob/4868c479cb13531f1fc8d607822bd39480310e1b/app/styles/sass/_tags.sass#L64

It's best practice to limit nesting depth to a maximum of 3. [sass-lint: nesting depth](https://github.com/sasstools/sass-lint/blob/master/docs/rules/nesting-depth.md)

It looks like this `header__calendar` element can be made into its own component. Please refactor the code to make a calendar block independent of the post styles.

**Comment by tokiroto** [comment]
Added changes ( commit 1a13b36c73422ea187e33138a9bdf38d3550ab84 ).

**Comment by ghost** [comment]
@tokiroto LGTM 👍
