### ISSUE TITLE
BEM elements

### ISSUE THREAD

**Issue by ghost** [tokiroto/HyakusenrenmaTestTask#5]
https://github.com/tokiroto/HyakusenrenmaTestTask/blob/4868c479cb13531f1fc8d607822bd39480310e1b/app/styles/sass/_tags.sass#L83

`.heading__content` and `.heading__subtext` appear to be unrelated block__elements of the `post__content` element. Consider renaming these classes.

**Comment by tokiroto** [comment]
Added changes ( commit bad0b48d871f8ed03be9fb81d5ad75b512a09fa0 ).

**Comment by ghost** [comment]
@tokiroto LGTM 👍
